# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifeq ($(MAIN),1)
unexport MAIN

# Main section

URCC = $(shell $(shell urweb -print-ccompiler) -print-prog-name=gcc)
URINCL = -I$(shell urweb -print-cinclude) 
.PHONY: all
all: ./easy-responsive-tabs.css.mk ./easy-responsive-tabs.css.urp
./easy-responsive-tabs.css.urp: ./Easy_responsive_tabs_css.ur ./Easy_responsive_tabs_css.urs ./Easy_responsive_tabs_css_c.h ./Easy_responsive_tabs_css_c.o ./easy-responsive-tabs.css.mk .cake3/tmp0
	cat .cake3/tmp0 > ./easy-responsive-tabs.css.urp
.cake3/tmp0: ./easy-responsive-tabs.css.mk
	-rm -rf .cake3/tmp0
	echo 'include ./Easy_responsive_tabs_css_c.h' >> .cake3/tmp0
	echo 'link ./Easy_responsive_tabs_css_c.o' >> .cake3/tmp0
	echo 'ffi ./Easy_responsive_tabs_css_c' >> .cake3/tmp0
	echo 'ffi ./Easy_responsive_tabs_css_js' >> .cake3/tmp0
	echo 'safeGet Easy_responsive_tabs_css/blobpage' >> .cake3/tmp0
	echo 'safeGet Easy_responsive_tabs_css/blob' >> .cake3/tmp0
	echo '' >> .cake3/tmp0
	echo './Easy_responsive_tabs_css' >> .cake3/tmp0
./Easy_responsive_tabs_css_c.o: ./Easy_responsive_tabs_css_c.c ./easy-responsive-tabs.css.mk $(call GUARD,URCC) $(call GUARD,URINCL) $(call GUARD,UR_CFLAGS)
	$(URCC) -c $(URINCL) $(UR_CFLAGS)  -o ./Easy_responsive_tabs_css_c.o ./Easy_responsive_tabs_css_c.c
$(call GUARD,URCC):
	rm -f .cake3/GUARD_URCC_*
	touch $@
$(call GUARD,URINCL):
	rm -f .cake3/GUARD_URINCL_*
	touch $@
$(call GUARD,UR_CFLAGS):
	rm -f .cake3/GUARD_UR_CFLAGS_*
	touch $@

else

# Prebuild/postbuild section

export MAIN=1

ifneq ($(MAKECMDGOALS),clean)

.PHONY: all
all: .fix-multy1
.PHONY: ./easy-responsive-tabs.css.urp
./easy-responsive-tabs.css.urp: .fix-multy1
.PHONY: .cake3/tmp0
.cake3/tmp0: .fix-multy1
.PHONY: ./Easy_responsive_tabs_css_c.o
./Easy_responsive_tabs_css_c.o: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: 
	-mkdir .cake3
	$(MAKE) -f ./easy-responsive-tabs.css.mk $(MAKECMDGOALS)

endif
.PHONY: clean
clean: 
	-rm ./Easy_responsive_tabs_css_c.o ./easy-responsive-tabs.css.urp .cake3/tmp0
	-rm -rf .cake3

endif
