# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifeq ($(MAIN),1)
unexport MAIN

# Main section

URCC = $(shell $(shell urweb -print-ccompiler) -print-prog-name=gcc)
URINCL = -I$(shell urweb -print-cinclude) 
.PHONY: all
all: ./jquery-ui.js.urp
./jquery-ui.js.urp: ./jquery-ui.js.urp.in
	cat ./jquery-ui.js.urp.in > ./jquery-ui.js.urp
./jquery-ui.js.urp.in: ./Jquery_ui_js.ur ./Jquery_ui_js.urs ./Jquery_ui_js_c.h ./Jquery_ui_js_c.o
	touch ./jquery-ui.js.urp.in
./Jquery_ui_js_c.o: ./Jquery_ui_js_c.c $(call GUARD,URCC) $(call GUARD,URINCL)
	$(URCC) -c $(URINCL)  -o ./Jquery_ui_js_c.o ./Jquery_ui_js_c.c
$(call GUARD,URCC):
	rm -f .cake3/GUARD_URCC_*
	touch $@
$(call GUARD,URINCL):
	rm -f .cake3/GUARD_URINCL_*
	touch $@

else

# Prebuild/postbuild section

export MAIN=1

.PHONY: all
all: .fix-multy1
.PHONY: ./jquery-ui.js.urp
./jquery-ui.js.urp: .fix-multy1
.PHONY: ./jquery-ui.js.urp.in
./jquery-ui.js.urp.in: .fix-multy1
.PHONY: ./Jquery_ui_js_c.o
./Jquery_ui_js_c.o: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: 
	-mkdir .cake3
	$(MAKE) -f ./jquery-ui.js.mk $(MAKECMDGOALS)

endif
