# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifdef MAIN

# Main section

URCC = $(shell $(shell urweb -print-ccompiler) -print-prog-name=gcc)
URINCL = $(shell urweb -print-cinclude)
.PHONY: all
all: ./jquery-ui.css.urp
./Jquery_ui_css_c.o: ./Jquery_ui_css_c.c $(call GUARD,URCC) $(call GUARD,URINCL)
	$(URCC) -c -I $(URINCL) -o ./Jquery_ui_css_c.o ./Jquery_ui_css_c.c
./jquery-ui.css.urp: ./Jquery_ui_css.ur ./Jquery_ui_css.urs ./Jquery_ui_css_c.h ./Jquery_ui_css_c.o
	touch ./jquery-ui.css.urp
$(call GUARD,URCC):
	rm -f .cake3/GUARD_URCC_*
	touch $@
$(call GUARD,URINCL):
	rm -f .cake3/GUARD_URINCL_*
	touch $@

else

# Prebuild/postbuild section

.PHONY: all
all: .fix-multy1
.PHONY: ./Jquery_ui_css_c.o
./Jquery_ui_css_c.o: .fix-multy1
.PHONY: ./jquery-ui.css.urp
./jquery-ui.css.urp: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: 
	-mkdir .cake3
	$(MAKE) -f ./jquery-ui.css.mk MAIN=1 $(MAKECMDGOALS)

endif
