# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifeq ($(MAIN),1)
unexport MAIN

# Main section

URCC = $(shell $(shell urweb -print-ccompiler) -print-prog-name=gcc)
URINCL = -I$(shell urweb -print-cinclude) 
.PHONY: all
all: ./jquery-ui.js.mk ./jquery-ui.js.urp
./jquery-ui.js.urp: ./Jquery_ui_js.ur ./Jquery_ui_js.urs ./Jquery_ui_js_c.h ./Jquery_ui_js_c.o ./jquery-ui.js.mk .cake3/tmp0
	cat .cake3/tmp0 > ./jquery-ui.js.urp
.cake3/tmp0: ./jquery-ui.js.mk
	-rm -rf .cake3/tmp0
	echo 'include ./Jquery_ui_js_c.h' >> .cake3/tmp0
	echo 'link ./Jquery_ui_js_c.o' >> .cake3/tmp0
	echo 'ffi ./Jquery_ui_js_c' >> .cake3/tmp0
	echo 'ffi ./Jquery_ui_js_js' >> .cake3/tmp0
	echo 'safeGet Jquery_ui_js/blobpage' >> .cake3/tmp0
	echo 'safeGet Jquery_ui_js/blob' >> .cake3/tmp0
	echo '' >> .cake3/tmp0
	echo './Jquery_ui_js' >> .cake3/tmp0
./Jquery_ui_js_c.o: ./Jquery_ui_js_c.c ./jquery-ui.js.mk $(call GUARD,URCC) $(call GUARD,URINCL) $(call GUARD,UR_CFLAGS)
	$(URCC) -c $(URINCL) $(UR_CFLAGS)  -o ./Jquery_ui_js_c.o ./Jquery_ui_js_c.c
$(call GUARD,URCC):
	rm -f .cake3/GUARD_URCC_*
	touch $@
$(call GUARD,URINCL):
	rm -f .cake3/GUARD_URINCL_*
	touch $@
$(call GUARD,UR_CFLAGS):
	rm -f .cake3/GUARD_UR_CFLAGS_*
	touch $@

else

# Prebuild/postbuild section

export MAIN=1

ifneq ($(MAKECMDGOALS),clean)

.PHONY: all
all: .fix-multy1
.PHONY: ./jquery-ui.js.urp
./jquery-ui.js.urp: .fix-multy1
.PHONY: .cake3/tmp0
.cake3/tmp0: .fix-multy1
.PHONY: ./Jquery_ui_js_c.o
./Jquery_ui_js_c.o: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: 
	-mkdir .cake3
	$(MAKE) -f ./jquery-ui.js.mk $(MAKECMDGOALS)

endif
.PHONY: clean
clean: 
	-rm ./Jquery_ui_js_c.o ./jquery-ui.js.urp .cake3/tmp0
	-rm -rf .cake3

endif
