# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifdef MAIN

# Main section

URCC = $(shell $(shell urweb -print-ccompiler) -print-prog-name=gcc)
URINCL = -I$(shell urweb -print-cinclude) 
.PHONY: all
all: ./jquery.megamenu.js.urp
./jquery.megamenu.js.urp: ./jquery.megamenu.js.urp.in
	cat ./jquery.megamenu.js.urp.in > ./jquery.megamenu.js.urp
./jquery.megamenu.js.urp.in: ./Jquery_megamenu_js.ur ./Jquery_megamenu_js.urs ./Jquery_megamenu_js_c.h ./Jquery_megamenu_js_c.o
	touch ./jquery.megamenu.js.urp.in
./Jquery_megamenu_js_c.o: ./Jquery_megamenu_js_c.c $(call GUARD,URCC) $(call GUARD,URINCL)
	$(URCC) -c $(URINCL) -o  ./Jquery_megamenu_js_c.o ./Jquery_megamenu_js_c.c
$(call GUARD,URCC):
	rm -f .cake3/GUARD_URCC_*
	touch $@
$(call GUARD,URINCL):
	rm -f .cake3/GUARD_URINCL_*
	touch $@

else

# Prebuild/postbuild section

.PHONY: all
all: .fix-multy1
.PHONY: ./jquery.megamenu.js.urp
./jquery.megamenu.js.urp: .fix-multy1
.PHONY: ./jquery.megamenu.js.urp.in
./jquery.megamenu.js.urp.in: .fix-multy1
.PHONY: ./Jquery_megamenu_js_c.o
./Jquery_megamenu_js_c.o: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: 
	-mkdir .cake3
	$(MAKE) -f ./jquery.megamenu.js.mk MAIN=1 $(MAKECMDGOALS)

endif
