# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifdef MAIN

# Main section

URCC = $(shell $(shell urweb -print-ccompiler) -print-prog-name=gcc)
URINCL = -I$(shell urweb -print-cinclude) 
.PHONY: all
all: ./nivo-arrows.png.urp
./nivo-arrows.png.urp: ./nivo-arrows.png.urp.in
	cat ./nivo-arrows.png.urp.in > ./nivo-arrows.png.urp
./nivo-arrows.png.urp.in: ./Nivo_arrows_png.ur ./Nivo_arrows_png.urs ./Nivo_arrows_png_c.h ./Nivo_arrows_png_c.o
	touch ./nivo-arrows.png.urp.in
./Nivo_arrows_png_c.o: ./Nivo_arrows_png_c.c $(call GUARD,URCC) $(call GUARD,URINCL)
	$(URCC) -c $(URINCL) -o  ./Nivo_arrows_png_c.o ./Nivo_arrows_png_c.c
$(call GUARD,URCC):
	rm -f .cake3/GUARD_URCC_*
	touch $@
$(call GUARD,URINCL):
	rm -f .cake3/GUARD_URINCL_*
	touch $@

else

# Prebuild/postbuild section

.PHONY: all
all: .fix-multy1
.PHONY: ./nivo-arrows.png.urp
./nivo-arrows.png.urp: .fix-multy1
.PHONY: ./nivo-arrows.png.urp.in
./nivo-arrows.png.urp.in: .fix-multy1
.PHONY: ./Nivo_arrows_png_c.o
./Nivo_arrows_png_c.o: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: 
	-mkdir .cake3
	$(MAKE) -f ./nivo-arrows.png.mk MAIN=1 $(MAKECMDGOALS)

endif
