# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifdef MAIN

# Main section

URCC = $(shell $(shell urweb -print-ccompiler) -print-prog-name=gcc)
URINCL = $(shell urweb -print-cinclude)
.PHONY: all
all: ./nivo-bullets.png.urp
./Nivo_bullets_png_c.o: ./Nivo_bullets_png_c.c $(call GUARD,URCC) $(call GUARD,URINCL)
	$(URCC) -c -I $(URINCL) -o ./Nivo_bullets_png_c.o ./Nivo_bullets_png_c.c
./nivo-bullets.png.urp: ./Nivo_bullets_png.ur ./Nivo_bullets_png.urs ./Nivo_bullets_png_c.h ./Nivo_bullets_png_c.o
	touch ./nivo-bullets.png.urp
$(call GUARD,URCC):
	rm -f .cake3/GUARD_URCC_*
	touch $@
$(call GUARD,URINCL):
	rm -f .cake3/GUARD_URINCL_*
	touch $@

else

# Prebuild/postbuild section

.PHONY: all
all: .fix-multy1
.PHONY: ./Nivo_bullets_png_c.o
./Nivo_bullets_png_c.o: .fix-multy1
.PHONY: ./nivo-bullets.png.urp
./nivo-bullets.png.urp: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: 
	-mkdir .cake3
	$(MAKE) -f ./nivo-bullets.png.mk MAIN=1 $(MAKECMDGOALS)

endif
