# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifeq ($(MAIN),1)
unexport MAIN

# Main section

URCC = $(shell $(shell urweb -print-ccompiler) -print-prog-name=gcc)
URINCL = -I$(shell urweb -print-cinclude) 
.PHONY: all
all: ./nivo-loading.gif.urp
./nivo-loading.gif.urp: ./nivo-loading.gif.urp.in
	cat ./nivo-loading.gif.urp.in > ./nivo-loading.gif.urp
./nivo-loading.gif.urp.in: ./Nivo_loading_gif.ur ./Nivo_loading_gif.urs ./Nivo_loading_gif_c.h ./Nivo_loading_gif_c.o
	touch ./nivo-loading.gif.urp.in
./Nivo_loading_gif_c.o: ./Nivo_loading_gif_c.c $(call GUARD,URCC) $(call GUARD,URINCL)
	$(URCC) -c $(URINCL)  -o ./Nivo_loading_gif_c.o ./Nivo_loading_gif_c.c
$(call GUARD,URCC):
	rm -f .cake3/GUARD_URCC_*
	touch $@
$(call GUARD,URINCL):
	rm -f .cake3/GUARD_URINCL_*
	touch $@

else

# Prebuild/postbuild section

export MAIN=1

.PHONY: all
all: .fix-multy1
.PHONY: ./nivo-loading.gif.urp
./nivo-loading.gif.urp: .fix-multy1
.PHONY: ./nivo-loading.gif.urp.in
./nivo-loading.gif.urp.in: .fix-multy1
.PHONY: ./Nivo_loading_gif_c.o
./Nivo_loading_gif_c.o: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: 
	-mkdir .cake3
	$(MAKE) -f ./nivo-loading.gif.mk $(MAKECMDGOALS)

endif
