# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifdef MAIN

# Main section

URCC = $(shell $(shell urweb -print-ccompiler) -print-prog-name=gcc)
URINCL = $(shell urweb -print-cinclude)
.PHONY: all
all: ./PikaChoose.js.urp
./PikaChoose.js.urp: ./PikaChoose_js.ur ./PikaChoose_js.urs ./PikaChoose_js_c.h ./PikaChoose_js_c.o
	touch ./PikaChoose.js.urp
./PikaChoose_js_c.o: ./PikaChoose_js_c.c $(call GUARD,URCC) $(call GUARD,URINCL)
	$(URCC) -c -I $(URINCL) -o ./PikaChoose_js_c.o ./PikaChoose_js_c.c
$(call GUARD,URCC):
	rm -f .cake3/GUARD_URCC_*
	touch $@
$(call GUARD,URINCL):
	rm -f .cake3/GUARD_URINCL_*
	touch $@

else

# Prebuild/postbuild section

.PHONY: all
all: .fix-multy1
.PHONY: ./PikaChoose.js.urp
./PikaChoose.js.urp: .fix-multy1
.PHONY: ./PikaChoose_js_c.o
./PikaChoose_js_c.o: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: 
	-mkdir .cake3
	$(MAKE) -f ./PikaChoose.js.mk MAIN=1 $(MAKECMDGOALS)

endif
