# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifeq ($(MAIN),1)
unexport MAIN

# Main section

URCC = $(shell $(shell urweb -print-ccompiler) -print-prog-name=gcc)
URINCL = -I$(shell urweb -print-cinclude) 
.PHONY: all
all: ./PikaChoose.css.urp
./PikaChoose.css.urp: ./PikaChoose.css.urp.in
	cat ./PikaChoose.css.urp.in > ./PikaChoose.css.urp
./PikaChoose.css.urp.in: ./PikaChoose_css.ur ./PikaChoose_css.urs ./PikaChoose_css_c.h ./PikaChoose_css_c.o
	touch ./PikaChoose.css.urp.in
./PikaChoose_css_c.o: ./PikaChoose_css_c.c $(call GUARD,URCC) $(call GUARD,URINCL)
	$(URCC) -c $(URINCL)  -o ./PikaChoose_css_c.o ./PikaChoose_css_c.c
$(call GUARD,URCC):
	rm -f .cake3/GUARD_URCC_*
	touch $@
$(call GUARD,URINCL):
	rm -f .cake3/GUARD_URINCL_*
	touch $@

else

# Prebuild/postbuild section

export MAIN=1

.PHONY: all
all: .fix-multy1
.PHONY: ./PikaChoose.css.urp
./PikaChoose.css.urp: .fix-multy1
.PHONY: ./PikaChoose.css.urp.in
./PikaChoose.css.urp.in: .fix-multy1
.PHONY: ./PikaChoose_css_c.o
./PikaChoose_css_c.o: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: 
	-mkdir .cake3
	$(MAKE) -f ./PikaChoose.css.mk $(MAKECMDGOALS)

endif
