# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifeq ($(MAIN),1)
unexport MAIN

# Main section

URCC = $(shell $(shell urweb -print-ccompiler) -print-prog-name=gcc)
URINCL = -I$(shell urweb -print-cinclude) 
.PHONY: all
all: ./Zoom.css.urp
./Zoom.css.urp: ./Zoom.css.urp.in
	cat ./Zoom.css.urp.in > ./Zoom.css.urp
./Zoom.css.urp.in: ./Zoom_css.ur ./Zoom_css.urs ./Zoom_css_c.h ./Zoom_css_c.o
	touch ./Zoom.css.urp.in
./Zoom_css_c.o: ./Zoom_css_c.c $(call GUARD,URCC) $(call GUARD,URINCL)
	$(URCC) -c $(URINCL)  -o ./Zoom_css_c.o ./Zoom_css_c.c
$(call GUARD,URCC):
	rm -f .cake3/GUARD_URCC_*
	touch $@
$(call GUARD,URINCL):
	rm -f .cake3/GUARD_URINCL_*
	touch $@

else

# Prebuild/postbuild section

export MAIN=1

.PHONY: all
all: .fix-multy1
.PHONY: ./Zoom.css.urp
./Zoom.css.urp: .fix-multy1
.PHONY: ./Zoom.css.urp.in
./Zoom.css.urp.in: .fix-multy1
.PHONY: ./Zoom_css_c.o
./Zoom_css_c.o: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: 
	-mkdir .cake3
	$(MAKE) -f ./Zoom.css.mk $(MAKECMDGOALS)

endif
