# This Makefile was generated by the ThirdCake
# https://github.com/grwlf/cake3

GUARD = .GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)
.PHONY: urp
urp: ./EremexImg.urp
./Banner_rtos_jpg_c.data.o: ./Banner_rtos_jpg_c_blob $(call GUARD,LD)
	$(LD) -r -b binary -o ./Banner_rtos_jpg_c.data.o ./Banner_rtos_jpg_c_blob
./Banner_rtos_jpg_c.o: ./Banner_rtos_jpg_c.c $(call GUARD,CC) $(call GUARD,UR_INCLUDE_DIR)
	$(CC) -c -I $(UR_INCLUDE_DIR) -o ./Banner_rtos_jpg_c.o ./Banner_rtos_jpg_c.c
./Banner_simone_jpg_c.data.o: ./Banner_simone_jpg_c_blob $(call GUARD,LD)
	$(LD) -r -b binary -o ./Banner_simone_jpg_c.data.o ./Banner_simone_jpg_c_blob
./Banner_simone_jpg_c.o: ./Banner_simone_jpg_c.c $(call GUARD,CC) $(call GUARD,UR_INCLUDE_DIR)
	$(CC) -c -I $(UR_INCLUDE_DIR) -o ./Banner_simone_jpg_c.o ./Banner_simone_jpg_c.c
./Banner_topor_jpg_c.data.o: ./Banner_topor_jpg_c_blob $(call GUARD,LD)
	$(LD) -r -b binary -o ./Banner_topor_jpg_c.data.o ./Banner_topor_jpg_c_blob
./Banner_topor_jpg_c.o: ./Banner_topor_jpg_c.c $(call GUARD,CC) $(call GUARD,UR_INCLUDE_DIR)
	$(CC) -c -I $(UR_INCLUDE_DIR) -o ./Banner_topor_jpg_c.o ./Banner_topor_jpg_c.c
./EremexImg.urp: ./EremexImg.urp.in
	cp ./EremexImg.urp.in ./EremexImg.urp
	echo ./EremexImg.urp
./EremexImg.urp.in: ./Banner_rtos_jpg.ur ./Banner_rtos_jpg.urp ./Banner_rtos_jpg.urs ./Banner_rtos_jpg_c.data.o ./Banner_rtos_jpg_c.h ./Banner_rtos_jpg_c.o ./Banner_rtos_jpg_c.urp ./Banner_rtos_jpg_c.urs ./Banner_rtos_jpg_js.urp ./Banner_rtos_jpg_js.urs ./Banner_simone_jpg.ur ./Banner_simone_jpg.urp ./Banner_simone_jpg.urs ./Banner_simone_jpg_c.data.o ./Banner_simone_jpg_c.h ./Banner_simone_jpg_c.o ./Banner_simone_jpg_c.urp ./Banner_simone_jpg_c.urs ./Banner_simone_jpg_js.urp ./Banner_simone_jpg_js.urs ./Banner_topor_jpg.ur ./Banner_topor_jpg.urp ./Banner_topor_jpg.urs ./Banner_topor_jpg_c.data.o ./Banner_topor_jpg_c.h ./Banner_topor_jpg_c.o ./Banner_topor_jpg_c.urp ./Banner_topor_jpg_c.urs ./Banner_topor_jpg_js.urp ./Banner_topor_jpg_js.urs ./EremexImg.ur ./EremexImg.urs ./Logo_gif.ur ./Logo_gif.urp ./Logo_gif.urs ./Logo_gif_c.data.o ./Logo_gif_c.h ./Logo_gif_c.o ./Logo_gif_c.urp ./Logo_gif_c.urs ./Logo_gif_js.urp ./Logo_gif_js.urs ./Logo_rtos_png.ur ./Logo_rtos_png.urp ./Logo_rtos_png.urs ./Logo_rtos_png_c.data.o ./Logo_rtos_png_c.h ./Logo_rtos_png_c.o ./Logo_rtos_png_c.urp ./Logo_rtos_png_c.urs ./Logo_rtos_png_js.urp ./Logo_rtos_png_js.urs ./Logo_simone_png.ur ./Logo_simone_png.urp ./Logo_simone_png.urs ./Logo_simone_png_c.data.o ./Logo_simone_png_c.h ./Logo_simone_png_c.o ./Logo_simone_png_c.urp ./Logo_simone_png_c.urs ./Logo_simone_png_js.urp ./Logo_simone_png_js.urs ./Logo_topor_png.ur ./Logo_topor_png.urp ./Logo_topor_png.urs ./Logo_topor_png_c.data.o ./Logo_topor_png_c.h ./Logo_topor_png_c.o ./Logo_topor_png_c.urp ./Logo_topor_png_c.urs ./Logo_topor_png_js.urp ./Logo_topor_png_js.urs
./Logo_gif_c.data.o: ./Logo_gif_c_blob $(call GUARD,LD)
	$(LD) -r -b binary -o ./Logo_gif_c.data.o ./Logo_gif_c_blob
./Logo_gif_c.o: ./Logo_gif_c.c $(call GUARD,CC) $(call GUARD,UR_INCLUDE_DIR)
	$(CC) -c -I $(UR_INCLUDE_DIR) -o ./Logo_gif_c.o ./Logo_gif_c.c
./Logo_rtos_png_c.data.o: ./Logo_rtos_png_c_blob $(call GUARD,LD)
	$(LD) -r -b binary -o ./Logo_rtos_png_c.data.o ./Logo_rtos_png_c_blob
./Logo_rtos_png_c.o: ./Logo_rtos_png_c.c $(call GUARD,CC) $(call GUARD,UR_INCLUDE_DIR)
	$(CC) -c -I $(UR_INCLUDE_DIR) -o ./Logo_rtos_png_c.o ./Logo_rtos_png_c.c
./Logo_simone_png_c.data.o: ./Logo_simone_png_c_blob $(call GUARD,LD)
	$(LD) -r -b binary -o ./Logo_simone_png_c.data.o ./Logo_simone_png_c_blob
./Logo_simone_png_c.o: ./Logo_simone_png_c.c $(call GUARD,CC) $(call GUARD,UR_INCLUDE_DIR)
	$(CC) -c -I $(UR_INCLUDE_DIR) -o ./Logo_simone_png_c.o ./Logo_simone_png_c.c
./Logo_topor_png_c.data.o: ./Logo_topor_png_c_blob $(call GUARD,LD)
	$(LD) -r -b binary -o ./Logo_topor_png_c.data.o ./Logo_topor_png_c_blob
./Logo_topor_png_c.o: ./Logo_topor_png_c.c $(call GUARD,CC) $(call GUARD,UR_INCLUDE_DIR)
	$(CC) -c -I $(UR_INCLUDE_DIR) -o ./Logo_topor_png_c.o ./Logo_topor_png_c.c
$(call GUARD,CC):
	rm -f .GUARD_CC_*
	touch $@
$(call GUARD,LD):
	rm -f .GUARD_LD_*
	touch $@
$(call GUARD,UR_INCLUDE_DIR):
	rm -f .GUARD_UR_INCLUDE_DIR_*
	touch $@
