# This Makefile was generated by the ThirdCake
# https://github.com/grwlf/cake3

GUARD = .GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)
.PHONY: urp
urp: ./PulsonixImg.urp
./Bluegreen_jpg_c.o: ./Bluegreen_jpg_c.c $(call GUARD,CC) $(call GUARD,UR_INCLUDE_DIR)
	$(CC) -c -I $(UR_INCLUDE_DIR) -o ./Bluegreen_jpg_c.o ./Bluegreen_jpg_c.c
./Flex_png_c.o: ./Flex_png_c.c $(call GUARD,CC) $(call GUARD,UR_INCLUDE_DIR)
	$(CC) -c -I $(UR_INCLUDE_DIR) -o ./Flex_png_c.o ./Flex_png_c.c
./Pencil_drawing_png_c.o: ./Pencil_drawing_png_c.c $(call GUARD,CC) $(call GUARD,UR_INCLUDE_DIR)
	$(CC) -c -I $(UR_INCLUDE_DIR) -o ./Pencil_drawing_png_c.o ./Pencil_drawing_png_c.c
./Pnp_png_c.o: ./Pnp_png_c.c $(call GUARD,CC) $(call GUARD,UR_INCLUDE_DIR)
	$(CC) -c -I $(UR_INCLUDE_DIR) -o ./Pnp_png_c.o ./Pnp_png_c.c
./PulsonixImg.urp: ./PulsonixImg.urp.in
	cp ./PulsonixImg.urp.in ./PulsonixImg.urp
	echo ./PulsonixImg.urp
./PulsonixImg.urp.in: ./Bluegreen_jpg.ur ./Bluegreen_jpg.urp ./Bluegreen_jpg.urs ./Bluegreen_jpg_c.h ./Bluegreen_jpg_c.o ./Bluegreen_jpg_c.urp ./Bluegreen_jpg_c.urs ./Bluegreen_jpg_js.urp ./Bluegreen_jpg_js.urs ./Flex_png.ur ./Flex_png.urp ./Flex_png.urs ./Flex_png_c.h ./Flex_png_c.o ./Flex_png_c.urp ./Flex_png_c.urs ./Flex_png_js.urp ./Flex_png_js.urs ./Pencil_drawing_png.ur ./Pencil_drawing_png.urp ./Pencil_drawing_png.urs ./Pencil_drawing_png_c.h ./Pencil_drawing_png_c.o ./Pencil_drawing_png_c.urp ./Pencil_drawing_png_c.urs ./Pencil_drawing_png_js.urp ./Pencil_drawing_png_js.urs ./Pnp_png.ur ./Pnp_png.urp ./Pnp_png.urs ./Pnp_png_c.h ./Pnp_png_c.o ./Pnp_png_c.urp ./Pnp_png_c.urs ./Pnp_png_js.urp ./Pnp_png_js.urs ./PulsonixImg.ur ./PulsonixImg.urs
$(call GUARD,CC):
	rm -f .GUARD_CC_*
	touch $@
$(call GUARD,UR_INCLUDE_DIR):
	rm -f .GUARD_UR_INCLUDE_DIR_*
	touch $@
